language: go

env:
  global:
    - DOCKER_IMAGE=$TRAVIS_REPO_SLUG
    - DOCKER_TAG=$TRAVIS_TAG

services:
  - docker

go:
  - 1.12

go_import_path: github.com/turbonomic/kubeturbo

before_install:
  - go get -v github.com/mattn/goveralls

script:
  - make fmtcheck
  - make vet
  - make build
  - $HOME/gopath/bin/goveralls -v -race -service=travis-ci
  - cp ./kubeturbo build
  - cd build
  - docker build -t $DOCKER_IMAGE --build-arg GIT_COMMIT=$TRAVIS_COMMIT --label "git-version=$TRAVIS_COMMIT" .

after_success:
  - |
    # Do not push images for builds triggered from pull requests
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      if [ -n "$TRAVIS_TAG" ]; then
          # Push a release image triggered by a git tag to Docker Hub
          docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$DOCKER_TAG
          docker push $DOCKER_IMAGE:$DOCKER_TAG
          # Also push to RH CC
          echo "$RHCC_PASSWORD" | docker login -u "$RHCC_USERNAME" "$RHCC_REGISTRY" --password-stdin
          RHCC_IMAGE=$RHCC_REGISTRY/$RHCC_REPO/$(basename $DOCKER_IMAGE)
          docker tag $DOCKER_IMAGE:$DOCKER_TAG $RHCC_IMAGE:$DOCKER_TAG
          docker push $RHCC_IMAGE:$DOCKER_TAG
      elif [ "$TRAVIS_BRANCH" == "master" ]; then
          # Push the latest image built from master branch
          docker push $DOCKER_IMAGE
      fi
    fi
