apiVersion: charts.helm.k8s.io/v1
kind: Kubeturbo
metadata:
  name: kubeturbo-meng
spec:
  # Default values copied from <project_dir>/helm-charts/kubeturbo/values.yaml
  
  # Default values for kubeturbo.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Turbo server version and address
  serverMeta:
    version: "8.1.6"
    turboServer: https://35.174.206.243:9403

  # Turbo server api user and password stored in a secret or optionally specified as username and password
  # The opsManagerUserName requires Turbo administrator role
  restAPIConfig:
    #turbonomicCredentialsSecretName: "turbonomic-credentials"
    opsManagerUserName: administrator
    opsManagerPassword: a

  roleBinding: "kubeturbo-meng-binding"
  serviceAccountName: "kubeturbo-meng"

  targetConfig:
    targetName: ocp-wdc02

  # Uncomment out lines to configure HA Node to ESX policies by node role. Default is master
  # Add more roles using format "\"foo\"\,\"bar\""
  #HANodeConfig:
  #  nodeRoles: "\"master\""

  # Uncomment next lines to specify a repository and image tag
  #image:
  #  repository: registry.connect.redhat.com
  #  tag: 8.0.0

  # Uncomment out to allow execution in OCP environments
  #args:
  #  sccsupport: "*"

  # Uncomment out to specify kubeturbo container specifications when needed (quotas set on ns)
  #resources:
  #  limits:
  #    memory: 4Gi
  #    cpu: "2"
  #  requests:
  #    memory: 512Mi
  #    cpu: "1"
